[package]
name = "gman-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "~1.3.3"
config = "~0.11.0"
log = "~0.4.14"
rand = { version = "0.8.5", features = ["small_rng"] }
regex = "1.5.4"
rustyline = "~8.2.0"
rustyline-derive = "0.4.0"
serde = "~1.0.126"
serde_derive = "~1.0.126"
tokio = { version = "~1.6.2", features = ["macros", "rt", "rt-multi-thread", "net", "io-util", "time", "sync"] }
tokio-serde = { version = "~0.8", features = ["bincode"] }
tokio-stream = { version = "~0.1.6", features = ["net"]}
tokio-util = { version = "~0.6.7", features = ["codec"] }