[package]
name = "gman-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "~1.0.126"
serde_derive = "~1.0.126"
rand = { version = "0.8.5", features = ["small_rng"] }